name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Deploy only when pushing to the main branch
    paths:
      - 'Podfile'
      - 'README.md'
      - '.github/workflows/**'
      - 'k8s/**'  # Update if anything changes in the k8s directory

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate with DigitalOcean
        env:
          DO_API_TOKEN: ${{ secrets.KUBECONFIG_BASE64 }}
        run: doctl auth init --access-token "$" secrets.KUBECONFIG_BASE64

      - name: Set up Kubernetes
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
        run: |
          echo "$KUBECONFIG_BASE64" | base64 --decode > ~/.kube/config
          chmod 600 ~/.kube/config
          export KUBECONFIG=~/.kube/config
          kubectl config use-context do-blr1-main-pool

      - name: Deploy iOS, Android, and Web Apps
        run: |
          kubectl apply -f k8s/ios/production.yml
          kubectl apply -f k8s/Android/production.yml
          kubectl apply -f k8s/web/production.yml

