name: Deploy to DigitalOcean Kubernetes

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
- name: Verify doctl Installation
  run: |
    if ! command -v doctl &> /dev/null; then
      echo "doctl not found, installing via Snap"
      sudo snap install doctl
    else
      echo "doctl is already installed"
    fi
    doctl version
      
          doctl version  # Verify installation

           - name: Configure kubectl
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }}
        run: |
          echo "$KUBECONFIG_BASE64" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config  # Secure kubeconfig file
          export KUBECONFIG=~/.kube/config  # Ensure kubectl uses this config
          kubectl config get-contexts  # Verify available contexts
          kubectl config use-context do-blr1-main-pool || kubectl config current-context


      - name: Deploy Web App
        run: kubectl apply -f k8s/web/production.yml

      - name: Deploy Android App
        run: kubectl apply -f k8s/Android/production.yml

      - name: Deploy iOS App
        run: kubectl apply -f k8s/ios/production.yml

